import {
  IconAngleDown,
  IconAngleUp,
  IconArrowLeft,
  IconCheck,
  IconChecklist,
  IconCompress,
  IconExpand,
  IconFlag,
  IconFloppy,
  IconMinus,
  IconMoreHorizontal,
  IconPause,
  IconPlay,
  IconPlus,
  IconRemove,
  IconReset,
  IconSquare,
  IconSquareDouble,
  IconStop,
  IconStopwatch,
  IconTimer,
  IconTrash } from 'components/common/Icons';

export const Icons = {
  'angle-down': IconAngleDown,
  'angle-up': IconAngleUp,
  'arrow-left': IconArrowLeft,
  'check': IconCheck,
  'checklist': IconChecklist,
  'compress': IconCompress,
  'expand': IconExpand,
  'flag': IconFlag,
  'floppy': IconFloppy,
  'minus': IconMinus,
  'more-horizontal': IconMoreHorizontal,
  'pause': IconPause,
  'play': IconPlay,
  'plus': IconPlus,
  'remove': IconRemove,
  'reset': IconReset,
  'square': IconSquare,
  'square-double': IconSquareDouble,
  'stop': IconStop,
  'stopwatch': IconStopwatch,
  'timer': IconTimer,
  'trash': IconTrash,
};
